### ISSUE TITLE
Zoom needs update breaks zoomrec

### ISSUE THREAD

**Issue by pieris98** [kastldratza/zoomrec#66]
**Describe the bug**
When trying to join a meeting, Zoom displays Update Zoom to continue window, demanding min version 5.13.5 to continue. I tried clicking update but it doesn't work and I don't know which version won't introduce errors to modify the Dockerfile accordingly.

**To Reproduce**
1. Join VNC 
2. Notice error on log board of zoomrec and possibly an already open Update Zoom window
3. Try to open zoom manually
4. Click on 'Join Meeting' and try to join meeting
5. See Update Zoom Window
6. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/kastldratza/zoomrec/assets/34139689/76d291a1-61a5-42ba-8b3e-6f5ed361adf8)
**Desktop (please complete the following information):**
 - OS: Debian 12
 - Version: Latest zoomrec docker image

**Additional context**
I was trying to navigate the cdn link but I couldn't find a version of 5.13.5. I also believe it might be a good idea to download the latest zoom client 5.16.6(382) to lengthen future proofness (given it doesn't introduce errors)

**Comment by takahashi-shotaro** [comment]
5.13.5 is here https://cdn.zoom.us/prod/5.13.5.363/zoom_amd64.deb
In 5.16.6, the font used in the application has changed, so we may need to retake the screenshots.

**Comment by pieris98** [comment]
> 5.13.5 is here https://cdn.zoom.us/prod/5.13.5.363/zoom_amd64.deb

Thank you for the link! I will try with this version to check if there are any errors.

> In 5.16.6, the font used in the application has changed, so we may need to retake the screenshots.

What do you mean retake screenshots? Is this needed for error handling or do you train some OCR model to identify the areas to click?

**Comment by takahashi-shotaro** [comment]
> What do you mean retake screenshots? Is this needed for error handling or do you train some OCR model to identify the areas to click?

Here are images to identify buttons and areas. https://github.com/kastldratza/zoomrec/tree/master/res/img

**Comment by Harald-Neumann** [comment]
After updating, I had a problem with the zoom/qt plugin xcb loading.
The problem was that pyautogui sets some qt environment variables, which cause Zoom to load pyQts version of xcb and not the normal one. I fixed it by `os.environ.copy()` and then deleting the qt related keys. Then pass it in as the env keyword argument in Popen.

Also, newer versions of pyautogui throw an exception when the image is not found, instead of returning None.

 Also, setting the environment variable `QT_DEBUG_PLUGINS=1` lets Zoom log more debug information.

I thought this might help if someone encounters similar problems.

**Comment by pieris98** [comment]
> I thought this might help if someone encounters similar problems.
@Harald-Neumann 
Hey Herald, thanks for the pointers! I actually still have problems with zoomrec after the update. Could you upload a docker image from your container (in case you have one)? Otherwise I'll try to reproduce the instructions you gave in your comment.

**Comment by Harald-Neumann** [comment]
> > I thought this might help if someone encounters similar problems.
> 
> Hey @Harald-Neumann , thanks for the pointers! I actually still have problems with zoomrec after the update. Could you please make a PR or fork branch? Also, could you upload a docker image from your container (in case you have one)? Otherwise I'll try to reproduce the instructions you gave in your comment.

I have created a [fork](https://github.com/Harald-Neumann/zoomrec). 
It uses the version of Zoom suggested by @takahashi-shotaro.

However, the changes are just quick and dirty, and the Python script is not adapted (in case there are any breaking changes in Zoom).
